services:
  backend:
    image: srajput2403/my-backend:v1
    build: ./backend
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: srajput2403/my-frontend:v1
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
